config/routes.rb
Rails.application.routes.draw do
  root 'flights#home'
  resources :flights, only: [:index]
  resources :bookings, except: [:index] do
    collection do
      get 'manage'
      get 'find'
    end
  end
  resources :users, only: [:create] do
    member do
      get 'bookings'
    end
  end
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/flight.rb
class Flight < ApplicationRecord
  validates :origin,
            :destination,
            :departure,
            :distance,
            :duration,
            :price,
            presence: true
  belongs_to :airline
  has_many :bookings

  def origin_airport
    Airport.find_by(code: origin)
  end

  def destination_airport
    Airport.find_by(code: destination)
  end

  def number
    airline.code + id.to_s
  end

  def departure_date(date)
    departure.change(
      year: date.year,
      month: date.month,
      day: date.day
    )
  end

  def arrival_date(date)
    departure_date(date) + duration.hours
  end

  def self.from_to(origin, destination)
    if destination.empty?
      where(origin: origin).order(price: :asc)
    else
      where(origin: origin, destination: destination).order(price: :asc)
    end
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def home
    @airports = Airport.airports_by_geography
  end

  def index
    @flights = Flight.from_to(params[:origin], params[:destination])
  end
end

app/helpers/flights_helper.rb
module FlightsHelper
  include Messages
  def check_search(origin, destination, date)
    errors = []
    errors << invalid_route if origin == destination
    check_date(date, errors)
    errors
  end

  private

  def check_date(date, errors)
    date = Time.parse(date)
    if date < Time.now
      errors << invalid_date_early
    elsif date > Time.now + 1.year
      errors << invalid_date_late
    end
  rescue ArgumentError
    errors << invalid_date_format
  end
end

app/views/flights/partials/_results_form.html.erb
    <%= form_tag new_booking_path, class: "row",
      method: 'get', id: "flight_view" do %>

      <% flights.each do |flight| %>

        <div class="col s12 m6 l4">
          <div class="z-depth-2" id="radios">
            <input class="flight_selector" name="flight" value=<%= flight.id %> type="radio" id=<%= flight.id %> />
            <%= label_tag 'flight_label', "Book this flight (#{flight.price} USD)", for: flight.id, class: "teal-text text-lighten-2", id: flight.id %>
          </div>
          <div>
            <%= render partial: "partials/flight", locals: { flight: flight, date: Time.parse(params[:date]) } %>
          </div>
        </div>

      <% end %>

      <%= hidden_field_tag "passengers_count", params[:passengers] %>
      <%= hidden_field_tag "departure", params[:date] %>

      <div class="input-field">
        <div class="col s12">
          <button id="select"
            class="btn waves-effect waves-light col s12 l12 z-depth-2"
              type="submit" id="select">Select Flight
            <i class="material-icons right">send</i>
          </button>
        </div>
      </div>

    <% end %>

app/views/flights/partials/_search_form.html.erb
<div class="row z-depth-3 hoverable" id="flight_form">
  <%= form_tag flights_path, method: 'get', id: "flight_forms", remote: true do %>

    <div class="col s12 l8">
      <div class="input-field">
        <%= select_tag(:origin, options_from_collection_for_select(@airports, :code, :formatted)) %>
        <%= label_tag("Origin") %>
      </div>

      <div class="input-field">
        <%= select_tag(:destination, options_from_collection_for_select(@airports, :code, :formatted), prompt: "Anywhere") %>
        <%= label_tag("Destination") %>
      </div>
    </div>

    <div class="col s12 l4">
      <div class="input-field">
        <%= select_tag(:passengers, options_for_select((1..9).to_a)) %>
        <%= label_tag("Passengers") %>
      </div>

      <div class="input-field">
        <input type="date" name="date" id= "date" class="datepicker">
      </div>
    </div>

    <div class="input-field col s12 l4 offset-l8">
      <button id="search" class="btn waves-effect waves-light col s12 l12 z-depth-1" type="submit">Search
        <i class="material-icons right">search</i>
      </button>
    </div>

  <% end %>
</div>