config/routes.rb
Rails.application.routes.draw do
  root 'flights#home'
  resources :flights, only: [:index]
  resources :bookings, except: [:index] do
    collection do
      get 'manage'
      get 'find'
    end
  end
  resources :users, only: [:create] do
    member do
      get 'bookings'
    end
  end
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/views/partials/_flashes.html.erb
<% flash.each do |name, msg| %>
  <script type="text/javascript">
    Materialize.toast('<%= msg %>', 4000, 'rounded');
  </script>
<% end %>

app/views/partials/_flight.html.erb
  <div class="card small horizontal z-depth-2 white-back">
    <div class="card-stacked">
      <div class="card-content">
        <div class="col s4 m4 l4 center-align light-blue-text text-darken-4">
          <h5 class="row"><%= flight.origin %></h5>
          <h6 class="row"><%= flight.departure.strftime "%H:%M" %></h6>
          <h6 class="row"><%= flight.origin_airport.city %></h6>
        </div>
        <div class="col s4 m4 l4 center-align">
          <i class="row material-icons center medium teal-text text-lighten-2">flight</i>
          <h6 class="row light-blue-text text-darken-4"><%= date.strftime "%Y-%m-%d" %></h6>
        </div>
        <div class="col s4 m4 l4 center-align light-blue-text text-darken-4">
          <h5 class="row"><%= flight.destination %></h5>
          <h6 class="row"><%= flight.arrival_date(date).strftime "%H:%M" %></h6>
          <h6 class="row"><%= flight.destination_airport.city %></h6>
        </div>
      </div>
      <div class="card-content center-align">
        <h6 class="row"><%= flight.airline.name %></h6>
        <h6 class="row">Flight Number: <%= flight.number %></h6>
        <h5 class="row teal-text lighten-2-text"><%= "#{flight.price} USD" %></h5>
      </div>
    </div>
  </div>

app/views/partials/_footer.html.erb
<footer class="light-blue darken-4 page-footer">
  <div class="container">
      <div class="row">
          <div class="col l6 s12">
              <h5 class="white-text">About Flyght</h5>
              <p class="grey-text text-lighten-4">
              Go from planning to booking your dream flight in minutes.</p>
          </div>
      </div>
  </div>
  <div class="footer-copyright">
      <div class="container ">
            © 2016 Flyght Inc.
      </div>
  </div>
</footer>

app/views/partials/_header.html.erb
<header>
<div class="navbar-fixed">
    <nav class="light-blue darken-4">
        <div class="nav-wrapper row container">
            <%= link_to "Flyght", root_path, class: "brand-logo", data: {turbolinks: false} %>
            <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
              <li><%= link_to "Manage Booking", find_bookings_path %></li>
              <% if current_user %>
                <li><%= link_to "Past Bookings", bookings_user_path(current_user) %></li>
                <li><%= link_to "Sign Out", logout_path, method: :delete, id: 'Sign Out' %></li>
              <% else %>
                <li><%= link_to "Sign Up", signup_path, id: 'Sign Up' %></li>
                <li><%= link_to "Log In", login_path %></li>
              <% end %>
            </ul>
            <ul class="side-nav" id="mobile-demo">
              <li><%= link_to "Manage Booking", find_bookings_path %></li>
              <% if current_user %>
                <li><%= link_to "Past Bookings", bookings_user_path(current_user) %></li>
                <li><%= link_to "Sign Out", logout_path, method: :delete, id: 'Sign Out' %></li>
              <% else %>
                <li><%= link_to "Sign Up", signup_path, id: 'Sign Up' %></li>
                <li><%= link_to "Log In", login_path %></li>
              <% end %>
            </ul>
        </div>
    </nav>
</div>
</header>