config/routes.rb
Rails.application.routes.draw do
  root 'flights#home'
  resources :flights, only: [:index]
  resources :bookings, except: [:index] do
    collection do
      get 'manage'
      get 'find'
    end
  end
  resources :users, only: [:create] do
    member do
      get 'bookings'
    end
  end
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/booking.rb
class Booking < ApplicationRecord
  include BookingsHelper

  belongs_to :flight
  belongs_to :user
  has_many :passengers, inverse_of: :booking, dependent: :destroy
  accepts_nested_attributes_for :passengers, allow_destroy: true
  validates :reference, :price, :departure, presence: true
  validates :email,
            presence: true,
            length: { maximum: 255 },
            format: { with: VALID_EMAIL }
  before_validation :generate_reference, :set_price, on: :create
  before_create :generate_reference, :set_price

  def generate_reference
    self.reference =
      "#{SecureRandom.hex(3)}/#{flight.id}/#{flight.number}".upcase
  end

  def set_price
    self.price = total_booking_cost(flight, passengers.size)
  end

  def expired?
    flight.departure_date(departure) < Time.now
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_booking_by_code, only: [:manage]
  before_action :find_booking_by_id, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:edit, :update, :destroy]

  def new
    flight = Flight.find_by(id: params[:flight])
    if flight
      @booking = flight.bookings.new
      @booking.departure = params[:departure]
      params[:passengers_count].to_i.times { @booking.passengers.build }
    else
      redirect_to(root_path, alert: no_flight_selected)
    end
  end

  def create
    flight = Flight.find_by(id: booking_params[:flight_id])
    @booking = flight.bookings.new(booking_params)
    if @booking.save
      BookingMailer.booking_confirmation(@booking).deliver_later
      redirect_to(@booking, alert: booking_saved)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @booking.update(booking_params)
      BookingMailer.booking_confirmation(@booking).deliver_later
      redirect_to(@booking, alert: booking_updated)
    else
      render 'edit'
    end
  end

  def destroy
    @booking.destroy
    redirect_to(bookings_user_path(current_user), alert: booking_deleted)
  end

  def manage
    if can_edit(@booking)
      redirect_to(edit_booking_path(@booking), alert: booking_found)
    else
      redirect_to(@booking, alert: booking_found)
    end
  end

  private

  def find_booking_by_id
    @booking = Booking.find(params[:id])
  end

  def find_booking_by_code
    @booking = Booking.find_by(reference: params[:ref].strip)
    @booking || record_not_found
  end

  def record_not_found
    redirect_to(find_bookings_path, alert: booking_not_found)
  end

  def can_edit(booking)
    current_user && current_user.email == booking.email
  end

  def booking_params
    params.require(:booking).permit(
      :email,
      :departure,
      :flight_id,
      :user_id,
      passengers_attributes: [:id, :name, :age, :passport, :phone]
    )
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
  def total_booking_cost(flight, passengers)
    (flight.price * passengers.to_i).round(2)
  end
end

app/views/bookings/edit.html.erb
<%= form_for (@booking) do |f| %>
<div class="container">
  <div class="row">

  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h4>
        <%= pluralize(@booking.errors.count, "error") %> found:
      </h4>
      <ul>
        <% @booking.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


    <h5 class="col s12 m12 l12 center-align">You're editing the below booking</h5>
    <h5 class="col s12 m12 l12 center-align">Total price for
      <%= @booking.passengers.size %> passenger(s): <%= @booking.price %> USD</h5>
    <div class="col s12 m4 l4 offset-m4 offset-l4">
      <%= render partial: "partials/flight", locals: { flight: @booking.flight, date: @booking.departure } %>
    </div>
    <h5 class="col s12 m12 l12 center-align">
      You can edit passenger information for your booking below
    </h5>

      <%= hidden_field_tag "booking[departure]", @booking.departure %>
      <%= hidden_field_tag "booking[flight_id]", @booking.flight_id %>
      <%= hidden_field_tag "booking[user_id]", current_user.id %>

      <ul>
        <%= f.fields_for :passengers do |passengers_form| %>
        <li>
          <div class="col s12 m6 l4" id="passenger">
            <div class="input-field">
              <%= passengers_form.label :name, "Full Names", class: "active" %>
              <%= passengers_form.text_field :name %>
            </div>
            <div class="input-field">
              <%= passengers_form.label :age, class: "active" %>
              <%= passengers_form.text_field :age %>
            </div>
            <div class="input-field">
              <%= passengers_form.label :passport, "Passport Number", class: "active" %>
              <%= passengers_form.text_field :passport %>
            </div>
            <div class="input-field">
              <%= passengers_form.label :phone, "Phone Number", class: "active" %>
              <%= passengers_form.text_field :phone %>
            </div>
          </div>
        </li>
        <% end %>
      </ul>

      <button id="search" class="btn waves-effect waves-light col s12 m12 l12" type="submit">Update Booking
        <i class="material-icons right">save</i>
      </button>

  </div>
</div>
<% end %>

app/views/bookings/find.html.erb
<div class="container">
   <div class="row">
      <%= form_tag manage_bookings_path, method: 'get', id: "booking_form", class: "col s12" do %>
      <div id="manage" class="col s12 m6 l6 offset-m3 offset-l3 z-depth-2">
         <h4 class="row center-align">Manage Booking</h4>
         <div class="row">
            <div class="input-field col s12">
              <i class="material-icons prefix">code</i>
               <%= label_tag :ref, "Confirmation Number" %>
               <%= text_field_tag :ref %>
            </div>
               <button id="search" class="btn waves-effect waves-light col s12 m4 l4 offset-m4 offset-l4" type="submit" id='Search'>Search
               <i class="material-icons right">search</i>
               </button>
         </div>
      </div>
      <% end %>
   </div>
</div>

app/views/bookings/manage.html.erb
<div class="container">
   <div class="row">
      <%= form_tag manage_bookings_path, method: 'get', id: "booking_form", class: "col s12" do %>
      <div id="manage" class="col s12 m6 l6 offset-m3 offset-l3 z-depth-2">
         <h4 class="row center-align">Manage Booking</h4>
         <div class="row">
            <div class="input-field col s12">
              <i class="material-icons prefix">code</i>
               <%= label_tag :ref, "Confirmation Number" %>
               <%= text_field_tag :ref %>
            </div>
               <button id="search" class="btn waves-effect waves-light col s12 m4 l4 offset-m4 offset-l4" type="submit">Search
               <i class="material-icons right">search</i>
               </button>
         </div>
      </div>
      <% end %>
   </div>
</div>

app/views/bookings/new.html.erb
<%= form_for @booking do |f| %>
<div class="container">
  <div class="row">

  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h4>
        <%= pluralize(@booking.errors.count, "error") %> found:
      </h4>
      <ul>
        <% @booking.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


    <h5 class="col s12 m12 l12 center-align">You've chosen to book the below flight.</h5>
    <h5 class="col s12 m12 l12 center-align">Total price for
      <%= @booking.passengers.size %> passenger(s): <%= total_booking_cost(@booking.flight, @booking.passengers.size) %> USD</h5>
    <div class="col s12 m4 l4 offset-m4 offset-l4">
      <%= render partial: "partials/flight", locals: { flight: @booking.flight, date: @booking.departure } %>
    </div>
    <h5 class="col s12 m12 l12 center-align">
      Please fill in the details for all passengers below then click on "Book Flight" to book the flight.
    </h5>

      <div class="input-field col s12 m12 l12">
      <% if current_user %>
        <%= f.text_field :email, type: :email, 'disabled value' => current_user.email %>
        <%= f.label :email, "Your email" %>
        <%= hidden_field_tag "booking[email]", current_user.email%>
      <% else %>
        <%= f.text_field :email, type: :email %>
        <%= f.label :email, "Your email" %>
      <% end %>
      </div>

      <div class="row" id="add-remove">
        <%= link_to "Add Passenger", new_booking_path(flight: @booking.flight.id, passengers_count: @booking.passengers.size + 1,  departure: @booking.departure ),
            class: "btn waves-effect waves-light col s8 m3 l3 offset-s2 offset-m2 offset-l2", id: "add" %>
        <%= link_to "Remove Passenger", new_booking_path(flight: @booking.flight.id, passengers_count: @booking.passengers.size - 1,  departure: @booking.departure ),
            class: "btn waves-effect waves-light col s8 m3 l3 offset-s2 offset-m2 offset-l2", id: "remove" unless @booking.passengers.size == 1 %>
      </div>

      <%= hidden_field_tag "passengers_count", @booking.passengers.size %>
      <%= hidden_field_tag "booking[departure]", @booking.departure %>
      <%= hidden_field_tag "booking[flight_id]", @booking.flight.id %>
      <%= hidden_field_tag "booking[user_id]", current_user_or_default.id %>


      <ul>
        <%= f.fields_for :passengers do |passengers_form| %>
        <li>
          <div class="col s12 m6 l4" id="passenger">
            <div class="input-field">
              <%= passengers_form.label :name, "Full Names" %>
              <%= passengers_form.text_field :name %>
            </div>
            <div class="input-field">
              <%= passengers_form.label :age %>
              <%= passengers_form.text_field :age %>
            </div>
            <div class="input-field">
              <%= passengers_form.label :passport, "Passport Number" %>
              <%= passengers_form.text_field :passport %>
            </div>
            <div class="input-field">
              <%= passengers_form.label :phone, "Phone Number" %>
              <%= passengers_form.text_field :phone %>
            </div>
          </div>
        </li>
        <% end %>
      </ul>

      <button id="search" class="btn waves-effect waves-light col s12 m12 l12" type="submit">Book Flight
        <i class="material-icons right">save</i>
      </button>

  </div>
</div>
<% end %>

app/views/bookings/show.html.erb
<div class="container">
  <div class="row">
    <h5 class="col s12 m12 l12 center-align"><%="Confirmation Number: #{@booking.reference}" %></h5>
    <h5 class="col s12 m12 l12 center-align"><%="Date Booked: #{@booking.updated_at.strftime '%Y-%m-%d %H:%M'}" %></h5>
    <h5 class="col s12 m12 l12 center-align">Total price: <%= @booking.price %> USD</h5>
    <div class="col s12 m4 l4 offset-m4 offset-l4">
      <%= render partial: "partials/flight", locals: {flight: @booking.flight, date: @booking.departure} %>
    </div>
    <h5 class="col s12 m12 l12 center-align">Here are the passengers booked for this flight</h5>

    <table class="striped col s12 m12 l12 center-align">
      <thead>
        <tr>
          <th data-field="name">NAME</th>
          <th data-field="age">AGE</th>
          <th data-field="passport">PASSPORT NUMBER</th>
          <th data-field="phone">PHONE NUMBER</th>
        </tr>
      </thead>
      <tbody>
        <% @booking.passengers.each do |passenger| %>
          <tr>
            <td><%= passenger.name %></td>
            <td><%= passenger.age %></td>
            <td><%= passenger.passport %></td>
            <td><%= passenger.phone %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>