config/routes.rb
Rails.application.routes.draw do
  root 'flights#home'
  resources :flights, only: [:index]
  resources :bookings, except: [:index] do
    collection do
      get 'manage'
      get 'find'
    end
  end
  resources :users, only: [:create] do
    member do
      get 'bookings'
    end
  end
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, :last_name, presence: true
  validates :password,
            presence: true,
            confirmation: true,
            length: { minimum: 6 }
  validates :password_confirmation, presence: true
  validates :email,
            uniqueness: true,
            presence: true,
            length: { maximum: 255 },
            format: { with: VALID_EMAIL }
  has_many :bookings

  has_secure_password

  def full_name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end

  def self.default_user
    User.find_or_create_by(email: 'default@flyght.com') do |user|
      user.first_name = 'Default'
      user.last_name = 'User'
      user.password = ENV['default_user_password']
      user.password_confirmation = ENV['default_user_password']
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:bookings]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to(root_path, notice: sign_up_welcome(@user))
    else
      render 'new'
    end
  end

  def bookings
    @bookings = current_user.bookings.order(updated_at: :desc)
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/bookings.html.erb
<div class="container">
  <div class="row">

    <% if @bookings.empty? %>
      <h5 class="center-align z-depth-2 rounded-header col s12 m6 l4 offset-m3 offset-l4">You have not made any bookings with Flyght yet</h5>
    <% else %>

    <h4 class="col s12 m6 l4 center-align rounded-header z-depth-2 offset-m3 offset-l4">Here are your past bookings</h4>
    <table class="striped col s12 m12 l12 center-align">
      <thead>
        <tr>
          <th data-field="origin">ORIGIN</th>
          <th data-field="destination">DESTINATION</th>
          <th data-field="date">DEPARTURE DATE</th>
          <th data-field="price">TOTAL PRICE</th>
          <th data-field="date_booked">DATE BOOKED</th>
          <th data-field="view">LINK TO VIEW</th>
          <th data-field="edit">LINK TO EDIT</th>
          <th data-field="delete">LINK TO CANCEL</th>
        </tr>
      </thead>
      <tbody>
        <% @bookings.each do |booking| %>
          <tr>
            <td><%= booking.flight.origin_airport.name %></td>
            <td><%= booking.flight.destination_airport.name %></td>
            <td><%= booking.departure.strftime '%Y-%m-%d' %></td>
            <td><%= "#{booking.price} USD" %></td>
            <td><%= booking.updated_at.strftime '%Y-%m-%d %H:%M' %></td>
            <td><%= link_to "View", booking %></td>
            <td><%= link_to "Edit", edit_booking_path(booking) %></td>
            <% if booking.expired? %>
              <td>EXPIRED</td>
            <% else %>
              <td><%= link_to "Cancel Booking", booking_path(booking), method: :delete, data: { confirm: "Are you sure you want to cancel this boooking?" }%></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <%= form_for @user, html: { class: "col s12" } do |f| %>

    <% if @user.errors.any? %>
    <div id="error_explanation">
      <h4>
        <%= pluralize(@user.errors.count, "error") %> found:
      </h4>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div id="sign-up">
    <h3 class="row center-align">Sign Up</h3>

    <div class="row">
      <div class="input-field col s12 l6">
        <i class="material-icons prefix">account_circle</i>
        <%= f.label :first_name, "First Name" %>
        <%= f.text_field :first_name %>
      </div>
      <div class="input-field col s12 l6">
        <i class="material-icons prefix">account_circle</i>
        <%= f.label :last_name, "Last Name" %>
        <%= f.text_field :last_name %>
      </div>
      <div class="input-field col s12">
        <i class="material-icons prefix">email</i>
        <%= f.label :email, "Email" %>
        <%= f.email_field :email %>
      </div>
      <div class="input-field col s12">
        <i class="material-icons prefix">security</i>
        <%= f.label :password, "Password" %>
        <%= f.password_field :password %>
      </div>
      <div class="input-field col s12">
        <i class="material-icons prefix">security</i>
        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation %>
      </div>
      <button class="btn waves-effect waves-light col s12 m4 l4 offset-m4 offset-l4" type="submit" id="Sign Up">Sign Up
        <i class="material-icons right">save</i>
      </button>
    </div>
    </div>
    <% end %>
  </div>
</div>